### ISSUE TITLE
In-processing Complete

### ISSUE THREAD

**Issue by RobertPorterfield** [OZI-SP-Dev/In-Out-Process#102]
Once the Supervisor selects the "Complete" button, an "In-processing Complete" notification shall be generated and sent to the Employee.

Condition:  The Supervisor selects the "Complete" button (this is prompted by the "Verify In-processing Complete" notification)

The email should have the following subject, where [Name] is the name of the in-processing employee from the GAL:  In-processing request for [Name] is now closed

The body of the email should be:
This email notification is to inform you that all in-processing tasks have been completed and the request closed.   

(AC1) When the Supervisor selects the "Complete" button indicating that all in-processing checklist items have been accomplished, this notification is automatically created/sent
(AC2) The notification will be sent to the Employee
(AC3) The notification confirms the completion and closure of the employees in-processing request.

**Comment by GregoryForrest** [comment]
Updated based on discussion with Eric
