### ISSUE TITLE
Rework employee selection UI

### ISSUE THREAD

**Issue by RobertPorterfield** [OZI-SP-Dev/In-Out-Process#43]
Approving, but after seeing it in action I don't think this is good UX. It was very rough for me to use, and I knew what to expect/do. The checkbox appearing above or below the name field (depending on if it is checked) was very confusing.
I think both the people picker and manual entry fields should be always visible.
People picker on top.
Selecting an item in the people picker pushes its title to the manual entry box.
Manual entry box is "required"
Not sure we even need the checkbox or not.

_Originally posted by @RobertPorterfield in https://github.com/OZI-SP-Dev/In-Out-Process/pull/42#pullrequestreview-1118718952_

**Comment by GregoryForrest** [comment]
Closed with PR #45
